#PBS -N detectron2_jpeg
#PBS -o /ghome/gaocs/DIICM/err_out/detectron2_jpeg.out
#PBS -e /ghome/gaocs/DIICM/err_out/detectron2_jpeg.err
#PBS -l nodes=1:gpus=1:S,walltime=350:00:00
#PBS -r y
cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes and gpus:
cat $PBS_NODEFILE
cat $PBS_GPUFILE

startdocker -u " -v /gdata/gaocs:/gdata/gaocs  -v /gdata1/gaocs:/gdata1/gaocs -v /gdata2/gaocs:/gdata2/gaocs " \
    -P /ghome/gaocs \
    -s "/ghome/gaocs/DIICM/job/detectron2.sh /gdata1/gaocs/Data_DIICM inferred MaskRCNN_Res101_FPN_0.5 jpeg_anchor transformed_compressed 0.5 70 60 50 40 30 20 10 1" \
    bit:5000/gaocs-detectron2

