MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "Res5ROIHeads"
DATASETS:
  # TRAIN: ("coco_2017_train",)
  # TEST: ("coco_2017_val",)
  TEST: ("coco_minVal2014_5000_Faster_Res50_C4_1.0_0.8_quality100", )
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
OUTPUT_DIR: /gdata1/gaocs/Data_DIICM/mAP/transformed/inferred/MaskRCNN_Res101_FPN_0.5/1.0_0.8/
VERSION: 2
